name: vitobongiorno
favicon: null
layout_spectrum: 0.2953139825258404
typography_spectrum: 0.5069166969042271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7087754644453526
  lightness: 0.2761168375145644
  saturation: 0.41841328982263803
  rhythmicContrast: 0.030892754206433892
purpose: []
